apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-gke
  labels:
    app: hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: helloworld-gke
        image: gcr.io/kpt-dev/helloworld-gke:0.1.3 # {"$ref":"#/definitions/io.k8s.cli.substitutions.image-tag"}
        ports:
        - name: http
          containerPort: 80
        env:
        - name: PORT
          value: "80"
